name: CI to DockerHub   #The name of the workflow
on:
  push:                 #on git push action
    branches: [ master ]

jobs:                   # the job is ran in github runner
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo      # validate the repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub # login to docker hub using defined credentials
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx  # setup the docker build
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push # build the image using the specified Dockerfile and push the image to Docker Hub with predefined tags
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flask:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}